### PR TITLE
Fixed issue #11

### PR DESCRIPTION
**Pull request by shivamsn97**
Added Spell Check and No Results Found to GUI

### CODE REVIEW

**Comment by aditeyabaral** [comment]
image

It by default starts with not found. Please find a way to fix this.

**Comment by aditeyabaral** [comment]
Also, when displaying the card for "Maybe you are looking for", display only 5 options.

**Comment by shivamsn97** [comment]
> 
> 
> image
> 
> It by default starts with not found. Please find a way to fix this.

Okay sure. Wait a few minutes.

**Comment by shivamsn97** [comment]
Fixed both these things in #13.

**Pull request merged**
