### PR TITLE
Webapp/GUI

### PR DESCRIPTION
**Pull request by tonybenoy**
Solves #1

### CODE REVIEW

**Comment by aditeyabaral** [comment]
Could you rework the GUI with any templates or make it prettier? It looks awfully bland and plain.

**Comment by tonybenoy** [comment]
Haha. Iteration v1 right. Do you have any themes in mind?

**Comment by aditeyabaral** [comment]
Hi!
Well here are a few things I'd like - 
* Viewing the results in the same page - it would be great if the results could be viewed in a scroll-able box on the same page, instead of redirecting to another. That way its easier to search for another word.
* The Header (Hi!, to be replaced with applicaiton name)could be in the middle on top, and you could separate the window into two frames down the centre. The left frame will have the search box and the button to search. The right frame can show the textbox which holds the results. 
* A material theme consisting of a blue colour scheme could look nice.
* Add prompts inside the textbox for the word search and remove "Word"
* Themes for buttons, more colourful. A slighly larger button and search box too.
* Replacing the "Hi!" with "PyDictionary"

**Comment by aditeyabaral** [comment]
Hi!
This looks good!
I'll create a new issue with some minor changes needed.

**Pull request merged**
