### PR TITLE
Add command line interface and other changes.

### PR DESCRIPTION
**Pull request by javim-h**
Add command line interface and improve README.md with information about dependencies and usage. Add requierements.txt file.

### CODE REVIEW

**Review by aditeyabaral — CHANGES_REQUESTED** [review]
Except nltk and pyenchant, the other additions are unnecessary.

**Review by aditeyabaral — CHANGES_REQUESTED** [review]
Do remove the comment added (telegram syntax comment)

**Review by aditeyabaral — COMMENTED** [review]
If possible, do add in a simple code markdown cell showing the input and the options available. If possible also do add in a "help" command.

**Comment by javim-h** [comment]
> Except nltk and pyenchant, the other additions are unnecessary.

I think that are necessary, I needed it under Arch Linux.

**Comment by aditeyabaral** [comment]
> 
> 
> > Except nltk and pyenchant, the other additions are unnecessary.
> 
> I think that are necessary, I needed it under Arch Linux.

Oh alright. My bad, Please make the other changes mentioned.

**Comment by aditeyabaral** [comment]
The issue is now closed.

**Comment by javim-h** [comment]
Removed old comment and added help option.

**Comment by javim-h** [comment]
Can you label it as hacktoberfest-accepted to count even if is not merged?

**Pull request closed without merging**
